In [1]:
import numpy as np
import pandas as pd

In [2]:
course_genre_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/course_genre.csv"
course_genres_df = pd.read_csv(course_genre_url)

In [3]:
course_genres_df.head()

,COURSE_ID,TITLE,Database,Python,CloudComputing,DataAnalysis,Containers,MachineLearning,ComputerVision,DataScience,BigData,Chatbot,R,BackendDev,FrontendDev,Blockchain
0,ML0201EN,robots are coming build iot apps with watson ...,0,0,0,0,0,0,0,0,0,0,0,1,1,0
1,ML0122EN,accelerating deep learning with gpu,0,1,0,0,0,1,0,1,0,0,0,0,0,0
2,GPXX0ZG0EN,consuming restful services using the reactive ...,0,0,0,0,0,0,0,0,0,0,0,1,1,0
3,RP0105EN,analyzing big data in r using apache spark,1,0,0,1,0,0,0,0,1,0,1,0,0,0
4,GPXX0Z2PEN,containerizing packaging and running a sprin...,0,0,0,0,1,0,0,0,0,0,0,1,0,0

In [4]:
profile_genre_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/user_profile.csv"
profile_df = pd.read_csv(profile_genre_url)

In [5]:
profile_df.head()

,user,Database,Python,CloudComputing,DataAnalysis,Containers,MachineLearning,ComputerVision,DataScience,BigData,Chatbot,R,BackendDev,FrontendDev,Blockchain
0,2,52.0,14.0,6.0,43.0,3.0,33.0,0.0,29.0,41.0,2.0,18.0,34.0,9.0,6.0
1,4,40.0,2.0,4.0,28.0,0.0,14.0,0.0,20.0,24.0,0.0,6.0,6.0,0.0,2.0
2,5,24.0,8.0,18.0,24.0,0.0,30.0,0.0,22.0,14.0,2.0,14.0,26.0,4.0,6.0
3,7,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
4,8,6.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,0.0,2.0,0.0,0.0,0.0

In [6]:
test_users_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMSkillsNetwork-ML0321EN-Coursera/labs/v2/module_3/ratings.csv"
test_users_df = pd.read_csv(test_users_url)

In [7]:
test_users_df.head()

      user        item  rating
0  1889878    CC0101EN       5
1  1342067    CL0101EN       3
2  1990814  ML0120ENv3       5
3   380098    BD0211EN       5
4   779563    DS0101EN       3

In [15]:
score_threshold = 10.0

In [14]:
all_courses = set(course_genres_df.COURSE_ID.values)
users = []
courses = []
scores = []

test_user_ids = test_users_df['user'].unique()
for user_id in test_user_ids:
    test_user_profile = profile_df[profile_df['user'] == user_id]
    test_user_vector = test_user_profile.iloc[:, 1:]
    enrolled_courses = test_users_df[test_users_df['user'] == user_id]['item'].to_list()
    unknown_courses = all_courses.difference(enrolled_courses)
    unknown_course_df = course_genres_df[course_genres_df['COURSE_ID'].isin(unknown_courses)]
    unknown_course_ids = unknown_course_df['COURSE_ID'].values
    recommendation_score = np.dot(unknown_course_df.iloc[:, 2:].values, np.asarray(test_user_vector).reshape(-1))
    for i in range(0, len(unknown_course_ids)):
        score = recommendation_score[i]
        if score > score_threshold:
            users.append(user_id)
            courses.append(unknown_course_ids[i])
            scores.append(score)

In [16]:
res_df = pd.DataFrame({
    'USER': users,
    'COURSE_ID': courses,
    'SCORE': scores
})
res_df.head()

      USER   COURSE_ID  SCORE
0  1889878    ML0201EN   12.0
1  1889878    ML0122EN   39.0
2  1889878  GPXX0ZG0EN   12.0
3  1889878  GPXX0Z2PEN   18.0
4  1889878    CNSC02EN   15.0